added the service,controller tests and made some endpoints
samuelowino/old-guard pull request #1
Opened 2023-12-21 12:30 UTC by masaGreen

So i have tried adding service and controller tests and then developed the service,repository and controller layers. I have learnt a lot from this exrcise especially test driven development. I will be glad to be corrected and learn.

Thanks for the chance of letting us learn from you man.

2023-12-21 15:22 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +    //TODO add dtos validations
Clean up pending TODOs. 
If you need help completing some of these, let me know

2023-12-21 15:38 UTC, samuelowino requested changes
Great job, @masaGreen! Your work is impressive, and it's evident that you've put a lot of thought and effort into it. I'm excited to see your contributions in action. If you have any questions or need further clarification on anything, don't hesitate to ask. I'm looking forward to the upcoming changes! Keep up the excellent work!

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +    //TODO add dtos validations
Clean up pending TODOs.
If you need help completing some of these, let me know

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +@RequestMapping("/api/v1/character")
You might need to use `/api/v1` in multiple controllers. Consider moving this to a constants, where it can be accessed by multiple controllers

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +    //can return single ShowCharacter or a list
Use multiline comments `/** .... **/` for the javadoc presentation

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +    //mimics ids handler on original api
Create a complete `javadoc` for this and other functions you want to describe

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +        if(ids.contains(",") || ids.contains("[")){
Write a validator or move this logic to the `service layer`

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/repository/CharacterRepository.java
> +
Consider removing the additional white spaces

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/service/CharacterManagementService.java
> +    private static final String API_DOMAIN = "http://domain";
Move to this to a constant class for use by other service classes

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/service/CharacterManagementService.java
> +    //find  characters matching a list of ids
Use javadoc syntax for these function descriptions. 
Check out this guide: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/service/CharacterManagementService.java
> +            System.out.println("noparams");
Use a `logger` for this instead of `sout`
Lombok contains `@Sl4j` logger. 
[Sl4j lombok project](https://projectlombok.org/api/lombok/extern/slf4j/Slf4j)

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/test/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterControllerTest.java
> +//        mockMvc = MockMvcBuilders.standaloneSetup(ShowCharacterController.class).setControllerAdvice()
Clear out any dead code

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/test/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterControllerTest.java
> +        //make the mocked service return charcter when called
Use `Junit @DisplayName` for test function description. It will help while executing the tests
https://junit.org/junit5/docs/5.0.3/api/org/junit/jupiter/api/DisplayName.html

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/test/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterControllerTest.java
> +                    .andExpect(jsonPath("$.name").value("Rick Sanchez"));
Include `MockMvcResultHandlers` - `.andDo(print())` which will help to visualise the mock http requests while executing the tests
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/web/servlet/result/MockMvcResultHandlers.html

2023-12-21 15:38 UTC, samuelowino commented on rickandmortyapi/src/test/java/com/oldguard/rickandmortyapi/service/CharacterManagementServiceTest.java
> +      @Test
Your code formatting is slightly off. 
What are you using as your editor or IDE? Feel free to add a code style config if you are using one

2023-12-21 16:11 UTC, masaGreen commented
Thank you alot for the feedback, I will revise them all. Am still learning
and this will really help me. I will reach out. Thank you again Sam.

On Thu, Dec 21, 2023, 6:38 PM Samuel Owino ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Great job, @masaGreen <https://github.com/masaGreen>! Your work is
> impressive, and it's evident that you've put a lot of thought and effort
> into it. I'm excited to see your contributions in action. If you have any
> questions or need further clarification on anything, don't hesitate to ask.
> I'm looking forward to the upcoming changes! Keep up the excellent work!
> ------------------------------
>
> In
> rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> <https://github.com/samuelowino/old-guard/pull/1#discussion_r1434205181>:
>
> > +
> +import com.oldguard.rickandmortyapi.dtos.CharactersDTO;
> +import com.oldguard.rickandmortyapi.dtos.CreateCharacterDTO;
> +import com.oldguard.rickandmortyapi.dtos.EditCharacterDTO;
> +import com.oldguard.rickandmortyapi.entities.ShowCharacter;
> +import com.oldguard.rickandmortyapi.service.CharacterManagementService;
> +import lombok.RequiredArgsConstructor;
> +import org.springframework.http.HttpStatus;
> +import org.springframework.http.ResponseEntity;
> +import org.springframework.web.bind.annotation.*;
> +
> ***@***.***
> ***@***.***("/api/v1/character")
> ***@***.***
> +public class ShowCharacterController {
> +    //TODO add dtos validations
>
> Clean up pending TODOs.
> If you need help completing some of these, let me know
> ------------------------------
>
> In
> rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> <https://github.com/samuelowino/old-guard/pull/1#discussion_r1434206289>:
>
> > @@ -0,0 +1,66 @@
> +package com.oldguard.rickandmortyapi.controllers;
> +
> +import com.oldguard.rickandmortyapi.dtos.CharactersDTO;
> +import com.oldguard.rickandmortyapi.dtos.CreateCharacterDTO;
> +import com.oldguard.rickandmortyapi.dtos.EditCharacterDTO;
> +import com.oldguard.rickandmortyapi.entities.ShowCharacter;
> +import com.oldguard.rickandmortyapi.service.CharacterManagementService;
> +import lombok.RequiredArgsConstructor;
> +import org.springframework.http.HttpStatus;
> +import org.springframework.http.ResponseEntity;
> +import org.springframework.web.bind.annotation.*;
> +
> ***@***.***
> ***@***.***("/api/v1/character")
>
> You might need to use /api/v1 in multiple controllers. Consider moving
> this to a constants, where it can be accessed by multiple controllers
> ------------------------------
>
> In
> rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> <https://github.com/samuelowino/old-guard/pull/1#discussion_r1434207918>:
>
> > +    @PostMapping("/create")
> +    public ResponseEntity<ShowCharacter> ***@***.*** CreateCharacterDTO createCharacterDTO){
> +        return new ResponseEntity<>(characterManagementService.saveCharacter(createCharacterDTO), HttpStatus.CREATED);
> +    }
> +
> +     @PutMapping("/edit/{id}")
> +    public ResponseEntity<ShowCharacter> ***@***.*** EditCharacterDTO editCharacterDTO, @PathVariable String id){
> +        return new ResponseEntity<>(characterManagementService.editCharacter(editCharacterDTO, id), HttpStatus.OK);
> +    }
> +
> +    @GetMapping("/findByName/{name}")
> +    public ResponseEntity<ShowCharacter> ***@***.*** String name){
> +        return new ResponseEntity<>(characterManagementService.findByName(name), HttpStatus.OK);
> +    }
> +
> +    //can return single ShowCharacter or a list
>
> Use multiline comments /** .... **/ for the javadoc presentation
> ------------------------------
>
> In
> rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> <https://github.com/samuelowino/old-guard/pull/1#discussion_r1434208555>:
>
> > +    public ResponseEntity<ShowCharacter> ***@***.*** CreateCharacterDTO createCharacterDTO){
> +        return new ResponseEntity<>(characterManagementService.saveCharacter(createCharacterDTO), HttpStatus.CREATED);
> +    }
> +
> +     @PutMapping("/edit/{id}")
> +    public ResponseEntity<ShowCharacter> ***@***.*** EditCharacterDTO editCharacterDTO, @PathVariable String id){
> +        return new ResponseEntity<>(characterManagementService.editCharacter(editCharacterDTO, id), HttpStatus.OK);
> +    }
> +
> +    @GetMapping("/findByName/{name}")
> +    public ResponseEntity<ShowCharacter> ***@***.*** String name){
> +        return new ResponseEntity<>(characterManagementService.findByName(name), HttpStatus.OK);
> +    }
> +
> +    //can return single ShowCharacter or a list
> +    //mimics ids handler on original api
>
> Create a complete javadoc for this and other functions you want to
> describe
> ------------------------------
>
> In
> rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> <https://github.com/samuelowino/old-guard/pull/1#discussion_r1434209278>:
>
> > +
> +     @PutMapping("/edit/{id}")
> +    public ResponseEntity<ShowCharacter> ***@***.*** EditCharacterDTO editCharacterDTO, @PathVariable String id){
> +        return new ResponseEntity<>(characterManagementService.editCharacter(editCharacterDTO, id), HttpStatus.OK);
> +    }
> +
> +    @GetMapping("/findByName/{name}")
> +    public ResponseEntity<ShowCharacter> ***@***.*** String name){
> +        return new ResponseEntity<>(characterManagementService.findByName(name), HttpStatus.OK);
> +    }
> +
> +    //can return single ShowCharacter or a list
> +    //mimics ids handler on original api
> +    @GetMapping("/{ids}")
> +    public  ResponseEntity<?> ***@***.*** String ids){
> +        if(ids.contains(",") || ids.contains("[")){
>
> Write a validator or move this logic to the service layer
> ------------------------------
>
> In
> rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/repository/CharacterRepository.java
> <https://github.com/samuelowino/old-guard/pull/1#discussion_r1434211544>:
>
> > @@ -9,4 +11,20 @@
>  @Repository
>  public interface CharacterRepository extends JpaRepository<ShowCharacter, Long> {
>      Optional<ShowCharacter> findByName(String name);
> +
> +    Optional<ShowCharacter> findByStatus(String status);
> +
> +
> +    Page<ShowCharacter> findAllByStatus( String status, Pageable pageable);
> +
> +
> +    Page<ShowCharacter> findByNameContainingIgnoreCase(String name, Pageable pageable);
> +
> +    Page<ShowCharacter> findByNameContainingIgnoreCaseAndStatusContainingIgnoreCase(String name, String status, Pageable pageable);
> +
> +    boolean existsByName(String name);
> +
>
> Consider removing the additional white spaces
> ------------------------------
>
> In
> rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/service/CharacterManagementService.java
> <https://github.com/samuelowino/old-guard/pull/1#discussion_r1434212901>:
>
> >  public class CharacterManagementService {
> +
> +    private final CharacterRepository characterRepository;
> +
> +    private static final String API_DOMAIN = "http://domain";
>
> Move to this to a constant class for use by other service classes
> ------------------------------
>
> In
> rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/service/CharacterManagementService.java
> <https://github.com/samuelowino/old-guard/pull/1#discussion_r1434214191>:
>
> > +    public String deleteById(String id){
> +        try {
> +            characterRepository.deleteById(Long.parseLong(id));
> +            return "deleted successfully";
> +        } catch (Exception e) {
> +            //should be handled better
> +            throw new RuntimeException(e.getMessage());
> +        }
> +    }
> +
> +    //find character by id
> +    public ShowCharacter findById(String id){
> +        return characterRepository.findById(Long.parseLong(id)).orElseThrow(
> +            ()-> new Ent [...]

2023-12-21 16:20 UTC, ayimdomnic commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +    //TODO add dtos validations
cut a ticket for the validation feature and link it to this PR, that way this work won't feel incomplete

2023-12-21 16:25 UTC, ayimdomnic commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +    @GetMapping("/findByName/{name}")
The endpoint /findByName/{name} follows a different naming convention compared to the others. Consider using a consistent naming pattern, such as /findBy/{name}. could be just me

2023-12-21 16:27 UTC, ayimdomnic commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +        return new ResponseEntity<>(characterManagementService.saveCharacter(createCharacterDTO), HttpStatus.CREATED);
Instead of creating a new ResponseEntity for successful responses, you can use `ResponseEntity.ok()`.

2023-12-21 17:45 UTC, samuelowino commented on rickandmortyapi/src/main/java/com/oldguard/rickandmortyapi/controllers/ShowCharacterController.java
> +    //TODO add dtos validations
👍🏿

2023-12-22 15:13 UTC, masaGreen commented
Hello, I have made the requested changes. Looking forward to hear your views.

2023-12-22 20:13 UTC, merged